// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwazltdvlnexwjqlhrum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3YXpsdGR2bG5leHdqcWxocnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Njc1MzAsImV4cCI6MjA2NDQ0MzUzMH0.P00unTqdWlf11ea_KFcpjl4LL8ObK-IoU49HtEruJfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);